# This pipeline shows how to:
# - Provision an Azure VM and register the VM in an Azure Pipelines environment.
# - Run a task like InstallNetCoreRuntimeAndHosting on the provisioned VM.
# - Remove the used Azure Pipelines environment and provisioned Azure resource group.
#
# The following variables need to be provided to the pipeline:
# - token           : a Personal Access Token with the scopes 'Environment (Read & manage)' and 'Tokens (Read & manage)'.
# - adminPassword   : a password for the admin user of the virtual machine.
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'MyAzureSubscription(f75e5af2-ade0-444e-8b38-221f69cbc9d8)'.


trigger: none
pr: none


variables:
  environmentName: "provision-vm-example-0002"


stages:
- stage: Provision
  jobs:
  - job:
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureSubscription(f75e5af2-ade0-444e-8b38-221f69cbc9d8)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az group create --name $(environmentName) --location japaneast;
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureSubscription(f75e5af2-ade0-444e-8b38-221f69cbc9d8)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az vm create `
            --name ProvisionedVM `
            --image UbuntuLTS `
            --admin-username azureuser `
            --location japaneast `
            --generate-ssh-keys `
            --resource-group $(environmentName);
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureSubscription(f75e5af2-ade0-444e-8b38-221f69cbc9d8)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          $customScriptUri = "https://raw.githubusercontent.com/blue0316/azure-pipeline-puppeteer/master/register-server-in-environment.sh";
          $customScriptSettings="{`\`"fileUris`\`":[`\`"$customScriptUri`\`"], `\`"commandToExecute`\`":`\`"sh ./register-server-in-environment.sh -OrganizationUrl '$(System.CollectionUri)' -TeamProject '$(System.TeamProject)' -Environment '$(environmentName)' -Token '$(token)'`\`"}";
          az vm extension set `
            --name CustomScriptExtension `
            --publisher Microsoft.Azure.Extensions `
            --vm-name ProvisionedVM `
            --resource-group $(environmentName) `
            --settings $customScriptSettings;


- stage: Test
  dependsOn: Provision
  condition: succeeded()
  jobs:
  - deployment: TestCustomTask
    environment:
      name: '$(environmentName)'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'
          - script: |
              git clone https://github.com/blue0316/puppeteer-test-project.git
            displayName: 'git clone'
            continueOnError: true
          - task: Npm@1
            displayName: 'install node packages'
            inputs:
              command: 'install'
              workingDir: 'puppeteer-test-project'
            continueOnError: true
          - task: Npm@1
            displayName: 'start test project'
            inputs:
              command: ci
              workingDir: 'puppeteer-test-project'
            continueOnError: true


- stage: Cleanup
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job:
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureSubscription(f75e5af2-ade0-444e-8b38-221f69cbc9d8)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          "$(token)" | az devops login --organization "$(System.CollectionUri)"

          $environmentId = az devops invoke `
            --area distributedtask `
            --resource environments `
            --route-parameters project="$(System.TeamProject)" `
            --org "$(System.CollectionUri)" `
            --api-version "6.0-preview" `
            --query "value[?name=='$(environmentName)'].id" `
            --output tsv

          az devops invoke `
            --area distributedtask `
            --resource environments `
            --route-parameters project="$(System.TeamProject)" environmentId=$environmentId `
            --org "$(System.CollectionUri)" `
            --http-method DELETE `
            --api-version "6.0-preview"
          
          az devops logout

          az group delete --name $(environmentName) --no-wait --yes